// Gmail Setup Helper Script
console.log("📧 GMAIL EMAIL SETUP HELPER");
console.log("============================");
console.log("");
console.log("🔐 STEP 1: Enable 2-Factor Authentication");
console.log("   Go to: https://myaccount.google.com/");
console.log('   Click "Security" → "2-Step Verification"');
console.log("   Enable 2-Factor Authentication");
console.log("");
console.log("🔑 STEP 2: Generate App Password");
console.log("   Go to: https://myaccount.google.com/apppasswords");
console.log('   Click "Select app" → "Mail"');
console.log('   Click "Generate"');
console.log("   Copy the 16-character password (like: abcd efgh ijkl mnop)");
console.log("");
console.log("⚙️  STEP 3: Update Server Configuration");
console.log("   Open: api/server-real-email.js");
console.log('   Find line 39: pass: "your-app-password-here"');
console.log('   Replace with: pass: "YOUR-16-CHAR-APP-PASSWORD"');
console.log("");
console.log("🚀 STEP 4: Start Real Email Server");
console.log("   Open terminal in api folder");
console.log("   Run: node server-real-email.js");
console.log("");
console.log("✅ STEP 5: Test");
console.log("   Go to: http://localhost:3000/index.html");
console.log("   Register with your real email");
console.log("   Check your email inbox for OTP");
console.log("");
console.log("📧 Your email: anantanarayansethy350@gmail.com");
console.log("");
console.log("⚠️  IMPORTANT:");
console.log("   - NEVER share your app password");
console.log("   - Keep your app password secure");
console.log("   - Remove spaces from app password when entering");
console.log("");
console.log("🎉 Once configured, you will receive REAL emails with OTP codes!");
